services:
  front:
    build: ./front
    container_name: zombieland-front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
       - ./front/node_modules:/app/node_modules
    depends_on:
      - back

    env_file:
      - ./front/.env.docker
    networks:
      - zombienet

  back:
    build: ./back
    container_name: zombieland-back
    command: >
      sh -c "npm run db:reset && npm run dev"
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://zombieland:zombieland@db:5432/zombieland
      PORT: 5000
    ports:                
      - "5000:5000" 
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - zombienet

  db:
    image: postgres:16-alpine
    container_name: zombieland-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: zombieland
      POSTGRES_PASSWORD: zombieland
      POSTGRES_DB: zombieland
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zombieland"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zombienet

volumes:
  pgdata:

networks:
  zombienet:
    driver: bridge
