@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiQWRtaW4iLCJsYXN0bmFtZSI6IlpvbWJpZSIsImVtYWlsIjoiYWRtaW5Aem9tYmllLmNvbSIsImFkbWluIjp0cnVlLCJpYXQiOjE3NTMxMTA5NTYsImV4cCI6MTc1MzE5NzM1Nn0.EOs7eScfeSVB-MqW0TNspwLZar1O_Uvu-nFEnXJZ85E

###
# Get all categories
GET http://localhost:5000/api/categories
###

###
# Get one categorie by id
GET http://localhost:5000/api/categories/1
###

# Create one categorie
POST http://localhost:5000/api/admin/categories
content-type: application/json
Authorization: Bearer {{token}}

{
    "name" : "123"

}
###

###
# Delete one categorie
DELETE http://localhost:5000/api/admin/categories/7
Authorization: Bearer {{token}}

###

###

###
# Update a categorie
PATCH http://localhost:5000/api/admin/categories/1
content-type: application/json
Authorization: Bearer {{token}}

{
    "name" : "sanglant"

}
###