@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkB6b21iaWUuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTc1MjE1MzIzNiwiZXhwIjoxNzUyMjM5NjM2fQ.f0nnVedcmA8JCf8PfY-UNvtm9YtbF925_mp-fKQxA3I

###
# Get all categories
GET http://localhost:5000/api/categories
###

###
# Get one categorie by id
GET http://localhost:5000/api/categories/1
###

# Create one categorie
POST http://localhost:5000/api/admin/categories
content-type: application/json
Authorization: Bearer {{token}}

{
    "name" : "123"

}
###

###
# Delete one categorie
DELETE http://localhost:5000/api/admin/categories/7
Authorization: Bearer {{token}}

###

###

###
# Update a categorie
PATCH http://localhost:5000/api/admin/categories/1
content-type: application/json
Authorization: Bearer {{token}}

{
    "name" : "sanglant"

}
###