@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJqaWRlMkBnbWFpbC5jb20iLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNzUyMDUzNTU5LCJleHAiOjE3NTIxMzk5NTl9.Kc1X-WEcg7jjEB5L3STNVC2WcY_CyawVWVCbD_w2-4s

###
# Get all reservations
GET http://localhost:5000/api/admin/reservations
Authorization: Bearer {{token}}

###

###
# Get one reservation by id
GET http://localhost:5000/api/admin/reservations
Authorization: Bearer {{token}}
###

# Create a reservation
POST http://localhost:5000/api/admin/reservations
content-type: application/json
Authorization: Bearer {{token}}

{
    "visit_date" : "2025-12-12",
    "nb_participants" : 5,
    "amount" : 200.01,
    "user_id" : 1
}
###

###
# Delete one reservation
DELETE http://localhost:5000/api/admin/reservations/6
Authorization: Bearer {{token}}
###

###

###
# Update a reservation
PATCH http://localhost:5000/api/admin/reservations/9
content-type: application/json
Authorization: Bearer {{token}}

{

    "nb_participants" : 21

}
###